### ISSUE TITLE
No output file generated

### ISSUE THREAD

**Issue by epysod12** [mickrideout/anafi-flightplan-utils#1]
Hello,

First of all, thank you for your approach and your work to convert flightplans for Anafi UAV!
I am trying to convert my recent Pix4Dcapture flightplan for FF6 App, but I encounter some problems.
The detail, step by step:

1. Download and extract **pix4d-flightplan-to-anafi** project
2. Go to `/home/<moi-même>/pix4d-flightplan-to-anafi-master/`
3. Type `lein uberjar`
4. Go to `target/uberjar`
5. Place the Pix4D JSON file (**details.pix4dcapture-mission**)
6. Run `java -jar anafi-flightplan-utils-0.1.0-SNAPSHOT-standalone.jar -i details.pix4dcapture-mission -o savedPlan.json`

Result: no file generated...
And the terminal says:
```
[]
Anafi flightplan utils.

Usage: anafi-flightplan-utils [options]

Options:
  -i, --input FILE                      Input file
  -o, --output FILE                     Output file
  -s, --speed SPEED         5           Speed m/s
  -p, --period SECS         2           Image capture period secs
  -t, --title TITLE         2022-12-12  Title of the flightplan
  -x, --homeLatitude LAT                latitude to return to
  -y, --homeLongitude LONG              longitude to return to
  -a, --homeAltitude ALT    50          Altitude to return to for home
  -h, --help                            Help
```

I tried several command combinations, but I can't get any output file.

Here is my setup:
- openSUSE Leap 15.4
- Clojure 1.10.3
- Leiningen 2.9.8

I am attaching the Pix4D file, is it the good one?
[details.pix4dcapture-mission.zip](https://github.com/mickrideout/pix4d-flightplan-to-anafi/files/10243980/details.pix4dcapture-mission.zip)
**EDIT:** And also the MAVLink file:
[flightPlan-2022-11-21.mavlink.zip](https://github.com/mickrideout/pix4d-flightplan-to-anafi/files/10243985/flightPlan-2022-11-21.mavlink.zip)
Or can you explain the exact command to type, please! Or tell me if I have forgotten a step somewhere?
Thanks in advance!

epysod12

**Comment by mickrideout** [comment]
Hi Epysod12,

Thank you for the bug report. I made some silly errors that meant an argument was required that wasnt documented. There was another bug if you didn't set the home coordinates, but I have fixed both of these now and committed the changes. If you pull the latest and run:   
```lein uber```   
then your command again it should work now. I tested the changes with your file and managed to produce this output:
[savedPlan.zip](https://github.com/mickrideout/pix4d-flightplan-to-anafi/files/10222799/savedPlan.zip)  

Let me know if you have any further problems. Happy flying

Michael

**Comment by epysod12** [comment]
Hi mickrideout,

Thanks, it works now! I can load the JSON file in FF6.
See picture:
![FlightPlan_20221214](https://user-images.githubusercontent.com/120389418/208050449-c30ced98-e4a3-45e8-a280-29850ac8a8ae.png)

Unfortunately, I can't test this flightplan at this location, construction work is now in progress...
[227018_Mersch_Welter](https://drone-est-captures.fr/3d-gallery/227018_Mersch_Welter/Mersch_Welter.html)

I edited my first message by adding the MAVLink file, I'll probably have more questions in the near future regarding file conversion.
Thank you for your quick answer!

epysod12
