### ISSUE TITLE
Options --speed or --period not working

### ISSUE THREAD

**Issue by epysod12** [mickrideout/anafi-flightplan-utils#2]
Hello,

I re-use data from the [#first issue](https://github.com/mickrideout/pix4d-flightplan-to-anafi/issues/1), and I try now to include the elements provided by the MAVLink file, such as **SPEED** and **INTERVAL**, whose values ​​are respectively found with the codes **178** (speed, m/s) and **50001** (distance interval, m).

Official documentation:
- code 178 -> [MAV_CMD_DO_CHANGE_SPEED](https://developer.parrot.com/docs/mavlink-flightplan/messages_v1.html#mav-cmd-do-change-speed)
- code 50001 -> [MAV_CMD_SET_STILL_CAPTURE_MODE](https://developer.parrot.com/docs/mavlink-flightplan/messages_v1.html#mav-cmd-set-still-capture-mode) and [MAV_STILL_CAPTURE_MODE_TYPE](https://developer.parrot.com/docs/mavlink-flightplan/enums.html#mav-still-capture-mode-type)

If _time = distance/speed_, here we have _time_ = 1.494963/1.000000 (in this case it's not difficult, but in another file I have _time_ = 4.318168/1.727267).

I invoke:
`java -jar anafi-flightplan-utils-0.1.0-SNAPSHOT-standalone.jar -i details.pix4dcapture-mission -o savedPlan.json -s 1 -p 1.5`
or
`java -jar anafi-flightplan-utils-0.1.0-SNAPSHOT-standalone.jar -i details.pix4dcapture-mission -o savedPlan.json --speed 1 --period 1.5`
... but nothing appeared (no file and no error message).

Can you investigate, please? Or tell me where I'm wrong!

Thank you for your attention,

epysod12

**Comment by mickrideout** [comment]
Hello,

Sorry for the delay on this issue I have been travelling.

I have just committed a bug fix for this issue. Please pull and build the latest code.

The following modified command will now work:  

`java -jar anafi-flightplan-utils-0.1.0-SNAPSHOT-standalone.jar -i details.pix4dcapture-mission -o savedPlan.json --speed 1 --period 1
`  

This differs from your command in that `--period 1.5` has to be a whole integer. e.g. `--period 1`  

Let me know how you get on.

mickrideout

**Comment by epysod12** [comment]
Hi mickrideout,

Thanks for your bug fix! It's still a pretty quick response time ;)
The command works perfectly with `--speed 1 --period 1` arguments, or any integer value.
Good work \o/

In FreeFlight6, **Speed** parameter only accept integer value, as we can see here:
![X01](https://user-images.githubusercontent.com/120389418/216340239-044208d4-56df-48c2-8afc-ca0caaa16676.png)

But for **Interval** parameter, we can put a decimal value in the specific field, like here:
![X02](https://user-images.githubusercontent.com/120389418/216340287-86516feb-ba17-47a6-a74c-c197227c72aa.png)

Do you think it's possible to allow decimal value for `--period` argument, and rounding precision to 1 digit for instance, such as `printf "%.1f" <value>`? (sorry, I'm not familiar with Clojure)
For example:
I type: `[...] --period 3.734 [...]` (at prompt)
I get: `[...] "period":3.7, [...]` (in JSON)

Some flightplans needs technical parameter with floating point numbers to achieve correctly overlap photography. It would be a definite gain if we could enter this type of value!

In another process, I take a look into Pix4D JSON file, to see how to extract interesting informations, and I wrote a small script (in Bash) which produces this kind of image:
![screenshot](https://user-images.githubusercontent.com/120389418/216360480-fb9e2f3a-eed6-4b29-9418-9ac958cda567.png)
Ideal to put in FF6 with the flightplan :D
A couple of weeks of review and documentation, and I can finally publish it...

Thanks in advance!

epysod12

**Comment by mickrideout** [comment]
Hi  epysod12,

I have changed the `--period` argument to take a decimal now instead of an integer. It will also perform precision rounding as per your suggestion.

Great work on the the flight image generator! A very useful tool indeed to visually validate flight plans!

Thanks

mickrideout

**Comment by epysod12** [comment]
Hi mickrideout,

Thanks for this adjustment! It allows a little more flexibility, especially for the number of photos we recover at the end of a mission ;)

On my side, I published the Bash code which makes it possible to obtain the image above. It also generates three CSV with the coordinates, distances, list of photos, etc.
Here is the script: [P4D_MissionAnalyser](https://gitlab.com/epysod12/p4d_missionanalyser)
And a short article: [Analyser son plan de vol avec P4D_MissionAnalyser](https://drone-est-captures.fr/2023/02/24/analyser-son-plan-de-vol-avec-p4d_missionanalyser/)
(english version coming soon...)

Have a nice day!

epysod12

**Comment by mickrideout** [comment]
Hi epysod12,

Great work on the mission analyser and write up. I would definitely be using this if my drone hadn't gone and smashed itself into the ground thanks to a propeller failure.

I hope I can use it soon though.

Take care

mickrideout

**Comment by epysod12** [comment]
Hi mickrideout,

Thank you for your encouragement.
In a way, your project is the source of my (humble) script!

Now, just a clarification on the behavior of P4D_MissionAnalyser:
The flightplan "must" have been executed in Pix4Dcapture (i.e. the mission completed) for the script to correctly parse the JSON file.
If not (and if the EPSG is specified), the script returns error messages but still calculates the total distance traveled between the waypoints (it's the **SUM_TOTAL** value in **sumDistWP.csv** file).

With this distance, other necessary information for the flightplan can be deduced therefrom. Here is a simple LibreCalc converter: [aerial_photogrammetry_calculations.ods](https://github.com/mickrideout/pix4d-flightplan-to-anafi/files/10882077/aerial_photogrammetry_calculations.ods)
(inspired from the Excel converter from robinh, in ParrotPilots forum: [Excel file from "robinh"](https://parrotpilots.com/threads/meshroom-is-effective-free-software-for-3d-scan.3394/#post-33129))

I just add a field with **Survey path**, and the formula _distance = time*speed_, as you can see below:
![Survey-Path_Field](https://user-images.githubusercontent.com/120389418/222726533-df639014-525d-4fd2-8ab3-62899003298d.png)

For example, if we have **357**m final value in **sumDistWP.csv** file, we can grope/experiment while entering other values until getting the right equation. And finally, using your program with the `--speed` and `--period` options, we have everything we need to generate an FF6 flightplan!

I continue to use your project, I hope you will (re-)find the use of your drone, it really has enormous potential!

epysod12
